INSERT INTO records (id, term, hours) VALUES (1, 'Introduction to mechanical ventilation', 5.00);
INSERT INTO records (id, term, hours) VALUES (2, 'Introduction to coronavirus disease 2019 (COVID-19)', 3.5);
INSERT INTO records (id, term, hours) VALUES (3, 'Clinical pointers: COVID-19 in primary care', 2.00);
INSERT INTO records (id, term, hours) VALUES (4, 'Clinical pointers: remote consultations in primary care', 1);
INSERT INTO records (id, term, hours) VALUES (5, 'Quick tips: introduction to asthma', 0);
INSERT INTO records (id, term, hours) VALUES (6, 'Infection control - including basic personal protective equipment', 10.25);
INSERT INTO records (id, term, hours) VALUES (7, 'Introduction to testing for COVID-19', 7.50);
INSERT INTO records (id, term, hours) VALUES (8, 'Airways management: tracheal intubation', 2.00);
INSERT INTO records (id, term, hours) VALUES (9, 'Quick tips: proning in critical care', 2.50);
INSERT INTO records (id, term, hours) VALUES (10, 'Quick tips: introduction to asthma', 3.0);